import 'package:flutter/material.dart';

// Déclare la liste globale en dehors de la classe
final List<Category> categories = [
  Category(
    name: 'Items non accepté',
    binColor: 'aucun', // Utilise une valeur spéciale pour cette catégorie
    icon: Icons.block,
    items: [
      'Gros meubles rembourrés ou non-rembourrés (fauteuils, divans, tables, chaises, étagères, lits, bureaux, unités murales…)',
      '(Voir en bas de page les organismes qui acceptent les dons de meubles)',
      'Gros appareils électroménagers (frigos, lave-vaisselle, laveuses, sécheuses, cuisinières…)',
      'Matelas et sommiers',
      'Pianos',
      'Tables de billard',
      'Combustibles (bidons d’essences et bonbonnes de gaz)',
      'Produits chimiques et d’entretien ménager',
      'Peinture, vernis, solvants',
      'Barrières et enceintes de sécurité',
      'Munitions et armes (armes à feu, armes blanches, armes de jet…)',
      'Vêtements endommagés',
      'Pneus',
      'Batteries de voiture',
      'Matériaux de construction',
      'Médicaments (déposez vos médicaments périmés dans n’importe quelle pharmacie)',
      'Portes et fenêtres en bois ou en verre',
      'Miroirs sans cadres',
      'Retailles de tissus et de tapis',
      'Sièges d’autos en mauvais état ou dont la date d’expiration est dépassée',
      'Denrées alimentaires (contactez les banques alimentaires près de chez vous)',
      'Articles promotionnels et uniformes avec logo d’entreprise',
      'Appareils CPAP',
      'Seringues',
      'Photocopieurs grand format',
      'Toilettes',
    ],
    directive: 'Ses objets ne sont pas acceptés par Renaissance.',
  ),
  // Bac gris
  Category(
    name: 'Accessoires',
    binColor: 'bleu',
    icon: Icons.umbrella,
    items: [
      'Petite-culotte (bobette, string, boxer, monokini)',
      'Foulard',
      'Tuque',
      'Écharpe',
      'Bas',
      'Bas de laine',
      'Bas collant',
      'Mitaine',
      'Gant',
      'Casquette',
      'Chapeau',
      'Lunettes',
      'Boîte à lunettes',
      'Bijoux (précieux, fantaisie)',
      'Ceinture',
      'Boucle de ceinture',
      'Implant mammaire',
      'Cravate',
      'Nœud papillon',
      'Porte-clé',
      'Petite serviette à main',
      'Débarbouillette',
      'Guenille',
      'Tissus',
      'Housse à oreiller (hors ensemble)',
      'Cosmétiques neufs',
      'Napperon',
      'Petite-culotte',
      'Bobette',
      'String',
      'Boxer',
      'Monokini',
      'Foulard en soie',
      'Foulard en coton',
      'Tuque en laine',
      'Tuque en acrylique',
      'Écharpe en cachemire',
      'Écharpe en polyester',
      'Bas de laine',
      'Bas en coton',
      'Bas collants',
      'Bas transparents',
      'Mitaine tricotée',
      'Mitaine polaire',
      'Gants en cuir',
      'Gants en laine',
      'Casquette de baseball',
      'Casquette plate',
      'Chapeau de paille',
      'Chapeau en feutre',
      'Lunettes de soleil',
      'Lunettes de vue',
      'Boîtier à lunettes',
      'Bracelet fantaisie',
      'Bracelet précieux',
      'Collier',
      'Bague',
      'Broche',
      'Boucles d’oreilles',
      'Ceinture en cuir',
      'Ceinture tressée',
      'Boucle de ceinture',
      'Cravate en soie',
      'Cravate tricotée',
      'Nœud papillon',
      'Porte-clé souvenir',
      'Porte-clé publicitaire',
      'Petite serviette à main',
      'Débarbouillette en coton',
      'Guenille microfibre',
      'Housse à oreiller (hors ensemble)',
      'Pochette maquillage',
      'Étui à bijoux',
      'Étui à lunettes',
      'Savon solide neuf',
    ],
    directive: 'Les bijoux doivent en tout temps être mis dans des sacs.',
  ),
  Category(
    name: 'Babioles',
    binColor: 'bleu',
    icon: Icons.account_box,
    items: [
      'Cadres',
      'Objets décoratifs',
      'Toiles',
      'Peintures(tableau)',
      'Articles artisanaux',
      'Chandeliers',
      'Bibelots',
      'Pots de fleurs ou de plantes',
      'Photos décoratives',
      'Cadre photo en métal',
      'Cadre photo en plastique',
      'Petite statuette en porcelaine',
      'Figurine en résine',
      'Bibelot en verre soufflé',
      'Bibelot en céramique',
      'Pot de fleurs',
      'Vase en céramique',
      'Vase en verre',
      'Bougeoir en métal',
      'Photophore en verre',
      'Photophore en métal',
      'Porte-bougie en céramique',
      'Miroir décoratif',
      'Tableau décoratif',
      'Toile peinte',
      'Affiche encadrée',
      'Masque mural décoratif',
      'Sculpture décorative en métal',
      'Masque décoratif en céramique',
      'Pot à crayons décoratif',
      'Assiette murale décorative',
      'Carreau décoratif mural',
      'Plaque décorative',
      'Globe terrestre de bureau',
      'Statuette religieuse',
      'Icône murale',
      'Porte-cartes décoratif',
      'Support à bijoux décoratif',
      'Ramequin décoratif',
      'Lot de petits pots en terre cuite',
      'Boîte à bijoux décorative',
      'Boule à neige souvenir',
      'Porte-encens en métal',
      'Photophore d’ambiance',
      'Plaque de bienvenue décorative',
      'Éventail décoratif plié',
      'Petit cadre multicadre',
      'Boîte à thé décorative',
      'Boîte à souvenirs',
      'Trophée décoratif',
      'Étagère hexagonale murale',
      'Sculpture de jardin miniature',
      'Bougeoir suspendu',
      'Mini-chevalet décoratif',
    ],
    directive: '',
  ),
  Category(
    name: 'Bois & Rotins',
    binColor: 'bleu',
    icon: Icons.deck,
    items: [
      'Objets décoratifs en écorce',
      'Objets décoratifs en bois',
      'Objets décoratifs en osier',
      'Cadre photo en bois',
      'Planche à découper en bois',
      'Spatule en bois',
      'Cuillère à soupe en bois',
      'Fourchette en bois',
      'Baguettes à sushi en bois',
      'Plateau de service en bois',
      'Plateau à fromage en bois',
      'Planche à fromage ronde en bois',
      'Boîte à bijoux en bois',
      'Coffret à thé en bois',
      'Petit coffre en bois',
      'Boîte à montre en bois',
      'Boîte à épices en bois',
      'Bloc à couteaux en bois (seulement si il n\'y a pas de couteau avec sinon le laisser ave les couteau dans objet tranchant)',
      'Porte-savon en bois',
      'Support brosse à dents en bois',
      'Bougeoir en bois',
      'Porte-bougie en bois',
      'Chandelier en bois',
      'Étagère murale flottante en bois',
      'Petite étagère à épices en bois',
      'Porte-revues en bois',
      'Crochet mural en bois',
      'Porte-manteau mural en bois',
      'Support casque audio en bois',
      'Support smartphone en bois',
      'Support tablette en bois',
      'Pot à crayons en bois',
      'Roulé-papier en bois',
      'Sous-verres en rotin',
      'Coasters en rotin',
      'Panier à pain en osier',
      'Panier à fruits en osier',
      'Petit panier de rangement en rotin',
      'Corbeille à papier en osier',
      'Corbeille à pain en osier',
      'Plateau ovale en rotin',
      'Boîte de rangement en rotin',
      'Tapis de table en rotin',
      'Set de table en rotin',
      'Napperon en osier',
      'Couvercle de boîte en osier',
      'Boîte tressée en osier',
      'Porte-serviettes en rotin',
      'Porte-revues en rotin',
      'Porte-clés mural en rotin',
    ],
    directive: 'Tout objet constitué à 75% et plus de bois.',
  ),
  Category(
    name: 'Cassette',
    binColor: 'bleu',
    icon: Icons.album,
    items: [
      'CD',
      'DVD',
      'BD-ROM',
      'Vinyles',
      'Jeux de console ou d’ordinateur',
      'Logiciels',
      'VHS',
      'Cassette vidéo',
      'VHS vierge',
      'Cassette Beta',
      'Film 3 mm',
      'CD audio',
      'CD-ROM logiciel Windows',
      'CD-ROM éducatif',
      'DVD',
      'Blu-ray',
      'UMD pour PSP',
      'Jeu PlayStation',
      'Jeu Xbox',
      'Jeu Xbox 360',
      'Jeu Xbox One',
      'Jeu Nintendo Switch',
      'jeux PC',
      'Jeux Nintendo 3DS',
      'Jeux Game Boy Advance',
      'Jeux Game Boy',
      'Jeux Game Boy Color',
      'Jeux Nintendo DS',
      'Cassette audio',
      'Lot de cassettes audio',
      'Cassette VHS',
      'Cassette VHS-C',
      'MiniDV',
      'Hi8',
      'Digital8',
      'Cassette Betamax',
      'DAT',
      'MiniDisc',
      'Disquette 3,5″',
      'Disquette 5,25″',
      'Zip Disk',
      'Zip Disk',
      'Zip Disk',
      'DVD-R vierge',
      'CD-R vierge',
      'CD-RW vierge',
      'DVD-RW vierge',
      'BD-ROM vierge',
    ],
    directive: '',
  ),
  Category(name: 'Chaussure', binColor: 'bleu', icon: Icons.directions_run, items: ['Chaussures (femmes, hommes, enfants)',
    'Bottes',
    'Sandales',
    'Souliers',
    'Espadrilles',
    'escarpins',], directive: ''),
  Category(
    name: 'Électronique/Électrique',
    binColor: 'bleu',
    icon: Icons.devices,
    items: [
      'Lampes',
      'Téléphones',
      'Lecteurs DVD',
      'Caméras',
      'Appareils culinaires',
      'Lampes de poche',
      'Réveils matin',
      'Montres',
      'Appareils audio/vidéo',
      'Ordinateurs portables',
      'Composants d’ordinateur',
      'Tablettes intelligentes',
      'Téléphone portable intelligent',
      'Montre intelligente',
      'iPod',
      'iPod touch',
      'iPad',
      'iPhone',
      'Lampe de bureau LED compacte',
      'Chargeur mural USB',
      'Adaptateur USB multiple',
      'Câble USB',
      'Souris filaire',
      'Souris sans fil',
      'Clavier sans fil',
      'Clavier d’ordinateur',
      'Webcam HD USB',
      'Casque audio filaire',
      'Casque audio sans fil',
      'Câble RCA',
      'Câble composite',
      'Câble VGA',
      'Câble DVI',
      'Câble coaxial',
      'Câble HDMI',
      'Câble audio jack 3,5 mm',
      'Câble audio jack 6,35 mm',
      'Câble optique',
      'Câble USB-C',
      'Câble internet',
      'Câble Ethernet',
      'Câble displayport',
      'Casque Bluetooth',
      'Écouteurs filaires',
      'Écouteurs intra-auriculaires',
      'Batterie externe (Power bank)',
      'Routeur Wi-Fi',
      'Modem ADSL',
      'Disque dur',
      'Disque dur externe 2,5"',
      'Disque dur externe 3,5"',
      'Clé USB',
      'carte microSD',
      'Carte SD',
      'Lecteur de cartes mémoire',
      'Télécommande TV',
      'Télécommande box Internet',
      'Station météo de bureau',
      'Enceinte Bluetooth portable',
      'Radio portable',
      'Lecteur DVD portable',
      'Lecteur Blu-ray',
      'Lecteur MP3',
      'Rasoir électrique',
      'Tondeuse à barbe compacte',
      'Brosse à dents électrique',
      'Ventilateur USB',
      'Mini-aspirateur USB',
      'Chauffe-mains électrique rechargeable',
      'Plaque à induction portable individuelle',
      'Fer à repasser de voyage',
      'Cafetière à dosettes',
      'Bouilloire électrique',
      'Grille-pain',
      'Mixeur',
      'Hachoir électrique',
      'Machine à expresso',
      'Diffuseur d’huiles essentielles',
      'Modem 4G (MiFi)',
      'Sèche-cheveux de voyage pliable',
      'Fer à lisser compact',
      'Déchiqueteuse de papier ',
      'Horloge numérique de table',
      'Réveil matin digital',
      'Balance électronique',
      'Balance numérique',
      'Mini-projecteur ',
      'projecteur',
      'Appareil photo numérique',
      'Caméra sport (GoPro ou équivalent)',
      'Caméra de surveillance',
      'Caméra de tableau de bord',

    ],
    directive: "Mettre dans cette catégorie tout objet qui fonctionne avec de l'électricité, qu'il soit filaire ou à batterie.",
  ),
  Category(name: 'Métal', binColor: 'bleu', icon: Icons.build, items: ['Fer',
    'Acier',
    'Stainless',
    'Aluminium',
    'Ustensiles en métal',
    'Casseroles',
    'Verres et tasses en métal',
    'Outils',
    'Cadenas',
    'Clous',
    'Vis',
    'Clés',
], directive: 'Tout objet constitué à 75% et plus de n’importe quel métal.'),
  Category(
    name: 'Plastique',
    binColor: 'bleu',
    icon: Icons.recycling,
    items: [
      'Assiettes en plastique',
      'Plats en plastique',
      'Verres en plastique',
      'Contenants en plastique',
      'Ustensiles en plastique',
      'Assiette plate en plastique',
      'Assiette creuse en plastique',
      'Assiette à dessert en plastique',
      'Bol en plastique dur',
      'Bol à soupe en plastique',
      'Bol à glace en plastique',
      'Gobelet réutilisable en plastique',
      'Tasse en plastique',
      'Mug de voyage en plastique',
      'Bouteille d’eau réutilisable en plastique',
      'Gourde en plastique',
      'Flacon distributeur de savon',
      'Flacon de shampooing/douche',
      'Boîte hermétique Tupperware',
      'Lunch box compartimentée en plastique',
      'Bac de rangement en plastique',
      'Organisateur de tiroir en plastique',
      'Bac à glaçons en plastique',
      'Passoire fine en plastique',
      'Passoire à gros trous en plastique',
      'Paire de pinces de cuisine en plastique',
      'Spatule en plastique',
      'Louche en plastique',
      'Cuillère mesure en plastique',
      'Fourchette en plastique dur',
      'Couteau en plastique dur',
      'Paire de pailles réutilisables en plastique',
      'Corne à pelle en plastique',
      'Entonnoir en plastique',
      'Arrosoir de table en plastique',
      'Porte-savon en plastique',
      'Distributeur de pâte dentifrice en plastique',
      'Porte-brosse à dents en plastique',
      'Séparateur de tiroir pour couverts en plastique',
      'Bac à courrier en plastique',
      'Corbeille à papier en plastique',
      'Boîte à couture en plastique',
      'Organiseur de bureau en plastique',
      'Gobelet à crayons en plastique',
      'Porte-cartes de visite en plastique',
      'Support à épices tournant en plastique',
      'Support mural à épices en plastique',
      'Bac de rangement empilable en plastique',
      'Plateau de rangement maquillage en plastique',
      'Tapis de souris rigide en plastique',
      'Étui de téléphone en plastique',
      'Support casque audio en plastique',
      'Mini-serre à semis en plastique',
    ],
    directive: 'Tout objet constitué à 75% et plus de tout type de plastique.',
  ),
  Category(
    name: 'Vaisselle',
    binColor: 'bleu',
    icon: Icons.kitchen,
    items: [
      'Vaisselle en vitre',
      'Vaisselle en porcelaine',
      'Verres en vitre, porcelaine ou cristal',
      'Coupes en vitre, porcelaine ou cristal',
      'Tasses en vitre et en porcelaine',
      'Assiette plate en porcelaine',
      'Assiette creuse en porcelaine',
      'Assiette à dessert',
      'Assiette à pain',
      'Assiette à salade',
      'Assiette à fruits',
      'Assiette à hors-d’œuvre',
      'Bol à céréales',
      'Bol à soupe',
      'Bol à dessert',
      'Bol à riz',
      'Tasse à café',
      'Soucoupe de tasse à café',
      'Tasse à thé',
      'Soucoupe de tasse à thé',
      'Mug en céramique',
      'Verre à eau',
      'Verre à jus',
      'Verre à vin rouge',
      'Verre à vin blanc',
      'Flûte à champagne',
      'Verre à bière',
      'Chope à bière',
      'Verre à whisky',
      'Verre à martini',
      'Verre à shot',
      'Coupe à dessert',
      'Coupe à fruits',
      'Soupière individuelle avec couvercle',
      'Petit plat rectangulaire de service',
      'Petit plat rond de service',
      'Plat à tarte individuel',
      'Plat à gratin individuel',
      'Plat à cake',
      'Saladier petit',
      'Plateau à sushi',
      'Ramequin',
      'Saucière',
      'Beurrier',
      'Sucrier',
      'Crémier',
      'Théière',
      'Cafetière à piston',
      'Carafe à eau',
      'Carafe à vin',
      'Pichet à jus',
      'Coupe à salade',
      'Plateau de service circulaire',
      'Tasse à espresso',
      'Soucoupe d’espresso',
    ],
    directive: '',
  ),
  Category(
    name: 'Sac',
    binColor: 'bleu',
    icon: Icons.shopping_bag,
    items: [
      'Sacs à main',
      'Sacs réutilisables',
      'Pochettes diverses',
      'Portemonnaie',
      'Portefeuille',
      'Sac à main en cuir',
      'Sac à main en toile',
      'Sac à bandoulière en tissu',
      'Tote bag',
      'Fourre-tout en coton',
      'Sac cabas pliable',
      'Sac réutilisable pour épicerie',
      'Sac à dos léger',
      'Sac à dos urbain',
      'Sac à dos pour enfant',
      'Sac à dos lavoie',
      'Sac à dos targus',
      'Sac à dos pour ordinateur portable',
      'Sac pour ordinateur portable',
      'Sac pour tablette intelligente',
      'Sac pour ipad',
      'Sacoche ordinateur en nylon',
      'Pochette tablette',
      'Étui smartphone',
      'Pochette enveloppe pour soirée',
      'Pochette à maquillage',
      'Trousse de toilette',
      'Pochette à crayons',
      'Trousse de premiers soins',
      'Pochette à bijoux',
      'Pochette ceinture',
      'Sac banane',
      'Sac à ceinture multifonction',
      'Portefeuille en cuir',
      'Portefeuille compact',
      'Porte-cartes',
      'Porte-monnaie',
      'Étui passeport',
      'Porte-documents souple',
      'Porte-documents',
      'Cartable pour enfant',
      'Serviette attaché-case',
      'attaché-case',
      'Mallette d’ordinateur compacte',
      'Mallette',
      'Housse d’instrument pliable',
      'Sac à boissons isotherme',
      'Sac à bento',
      'Pochette pour outils de couture',
      'Pochette pour appareil photo',
      'Sac pour drones et accessoires',
      'Sac de yoga',
      'Sac de sport compact',
      'Sac de golf pour accessoires',
      'Sac à casque de vélo',
      'Sac à casque audio',
      'Sac à lunch isotherme',
      'Sac pour bouteilles de vin',
      'Sac pour bouteilles d’eau',
      'Sac à gants de boxe',
      'Sac à roulettes',
      'sac réutilisable',
    ],
    directive: '',
  ),
  Category(name: 'Sport', binColor: 'bleu', icon: Icons.sports, items: [
      'Articles de sport (casque, protection)',
      'Équipement de hockey',
      'Balles de golf',
      'Balles de baseball',
      'Ballons de soccer, football, basketball',
      'Patins à roulettes',
      'Patins à glace',
      'Raquettes de tennis',
      'Raquettes de badminton',
      'Ballon de soccer',
      'Ballon de basketball',
      'Ballon de volleyball',
      'Ballon de football',
      'Ballon de rugby',
      'Ballon de handball',
      'Balle de tennis',
      'Lot de 3 balles de tennis',
      'Lot de 6 volants de badminton',
      'Raquette de squash',
      'Set de ping-pong',
      'Raquette de ping-pong',
      'Balle de ping-pong',
      'Corde à sauter',
      'Bande de résistance élastique',
      'Haltère ajustable',
      'Poignées de traction pour fitness',
      'Parallettes',
      'Roue abdominale',
      'Tapis de yoga',
      'Bloc de yoga en mousse',
      'Bande élastique pour gymnastique',
      'Balle de massage',
      'Petit ballon de gym',
      'Bâtons de ski',
      'Chaussures d’escalade',
      'Harnais d’escalade compact',
      'Mousquetons',
      'Casque de vélo',
      'Casque de hockey',
      'Protège-tibias',
      'Protège-coudes',
      'Gants de cyclisme',
      'Gants de boxe',
      'Protège-poignets',
      'Genouillères',
      'Coudières',
      'Petit sac de sport',
      'Guêtres de course',
      'Ceinture porte-bidon',
      'Bidon de sport',
      'Serviette micro-fibre de sport',
      'Lunettes de natation',
      'Palmes courtes',
      'Mini-palmes',
      'Planche de natation',
      'Pompe à main pour ballons',
      'Sifflet sportif',
      'Chronomètre numérique de poche',
      'Frisbee',
    ],
    directive: '',
  ),
  Category(
    name: 'Papeterie',
    binColor: 'bleu',
    icon: Icons.edit,
    items: [
      'Papier vierge',
      'Feuilles lignées',
      'Livres à colorier',
      'Duo-tang',
      'Cartables',
      'Articles à dessin',
      'Stylos',
      'Crayons de couleur',
      'Craies',
      'Gommes à effacer',
      'Crayons de cire',
      'Feuilles de plastique',
      'Cartons de coloriage',
      'Cartons d’impression',
      'Papiers photo',
      'Marqueurs',
      'Papiers d’emballage',
      'Rouleaux à monnaie',
      'Albums photo',
      'Cartes de souhait',
      'Étuis à crayon',
      'Brocheuses',
      'Punaises',
      'Fournitures de bureau',
      'Feuilles ligné',
      'Feuilles blanches',
      'Bloc-notes autocollant',
      'Post-it',
      'Carnet à spirale',
      'Carnet de croquis',
      'Duo-tang en plastique',
      'Chemise à élastique',
      'Pochette perforée',
      'Cartable rigide à anneaux',
      'Classeur à anneaux',
      'Intercalaires pour classeur',
      'Cahier de notes',
      'Cahier quadrillé',
      'Cahier à spirale',
      'Cahier d’exercices',
      'Carnet de dessins',
      'Stylo à bille',
      'Stylo gel',
      'Stylo plume',
      'Crayon HB',
      'Crayon 2B',
      'Crayon de couleur',
      'Crayons-feutres',
      'Surligneur',
      'Marqueur indélébile',
      'Marqueur effaçable à sec',
      'Gomme à effacer',
      'Taille-crayon double',
      'Distributeur de ruban adhésif',
      'Rouleau de ruban adhésif transparent',
      'Rouleau de ruban adhésif résistant',
      'Colle bâton',
      'Colle blanche liquide',
      'Agrafeuse de bureau compact',
      'Boîte d’agrafes',
      'Trombones',
      'Punaise',
      'Élastiques',
      'Œillets adhésifs',
      'Étiquettes autoadhésives',
      'Étiqueteuse portable',
      'Règle 30 cm',
      'Rapporteur 15 cm',
      'Équerre 20 cm',
      'Set de pochoirs géométriques',
      'Pochette à crayons',
      'Trousse d’écolier',
      'marqueur permanent',
    ],
    directive: 'Mettre les crayons ensemble dans un sac et les petits articles en grosse quantité qui ne sont plus dans leur emballage.',
  ),
  Category(name: 'Objets tranchants', binColor: 'bleu', icon: Icons.kitchen, items: ['Couteaux',
    'Ciseaux',
    'Marteaux',
    'Scies',
    'Pics',
    'Haches',
    'Épées',
    'Tire-bouchons',
    'Couteaux de poche (canif)',
    'Tout autre objet tranchant et perforant'], directive: 'Tous les objets et uniquement les objets avec lesquels on risque de pouvoir se couper d’une manière ou d’une autre ainsi que les objets à bout pointu présentant un risque de se blesser.'),
  Category(name: 'Halloween', binColor: 'bleu', icon: Icons.emoji_emotions, items: ['Décorations d’Halloween',
    'Masques',
    'Déguisements',
    'Maquillage d’Halloween',
  ], directive: 'Tout article d’Halloween, luminaire compris.'),
  Category(name: 'Noël', binColor: 'bleu', icon: Icons.park, items: ['Décorations de Noël',
    'Luminaire de Noël',
    'Figurines de Noël',], directive: 'Tout article qui concerne Noël, luminaire compris.'),
  Category(
    name: 'Jouets',
    binColor: 'bleu',
    icon: Icons.toys,
    items: [
      'Petit jouet',
      'Jeux de cartes',
      'Jeux de société',
      'Casse-tête',
      'Toutou',
      'Carte à jouer (Pokémon, Magic, etc.)',
      'Jouets pour enfant',
      'Accessoire de jeu',
      'Figurine',
      'Sabre en mousse',
      'Marionnette',
      'Yo-yo',
      'Cube magique',
      'Balle rebondissante',
      'Toupie',
      'Diabolo',
      'Boomerang',
      'Dé à jouer',
      'Piste de course électrique',
      'Poupée',
      'Peluche moyenne',
      'Poupée de chiffon',
      'Figurine d’action',
      'Voiture miniature',
      'Train miniature',
      'Jeu de cartes UNO',
      'Jeu de cartes standard',
      'Cartes à collectionner',
      'Casse-tête 500 pièces',
      'Puzzle 1000 pièces',
      'Set LEGO basique',
      'Mini-set LEGO',
      'Blocs de construction en bois',
      'Jouet en bois – voiture',
      'Playmobil',
      'Puzzle en bois',
      'Jeu de société de voyage',
      'Dominos',
      'Mikado',
      'Cerceau pliable',
      'Balle en mousse',
      'Ballon de plage',
      'Frisbee',
      'Sifflet jouet',
      'Trompette en plastique',
      'Maracas',
      'Tambourin',
      'Xylophone jouet',
      'Kit de pâte à modeler',
      'Set de peinture pour enfants',
      'Pinceaux pour enfants',
      'Tableau blanc effaçable',
      'Feutres effaçables',
      'Livre d’images pour enfants',
      'Livre sonore pour enfants',
      'Figurine Funko Pop',
      'Voiture télécommandée miniature',
      'Hélicoptère jouet',
      'Mini-drone',
      'Puzzle 3D',
      'Tente pour enfants pliable',
      'Tunnel de jeu pliable',
      'Marionnettes',
      'Mini-instruments de musique',
      'Jeu d’équilibre',
      'Rubik’s Cube',
      'Jeu de quilles miniature',
    ],
    directive: '',
  ),
  Category(name: 'Livres', binColor: 'bleu', icon: Icons.book, items: ['Livre',
    'Revue',
    'Livre scolaire',
    'Dictionnaire',
    'roman',
    'encyclopédie',
  ], directive: 'Tout livre qui sert uniquement à être lu.'),
  Category(name: 'Denrée non périssable', binColor: 'bleu', icon: Icons.ramen_dining, items: ['conserve',
      'nourriture emballer sous vide',
    ], directive: ''),
  Category(name: 'PCD Produits corrosifs', binColor: 'bleu', icon: Icons.warning, items: [
      'agent de blanchiment à base de chlore',
      'Javellisants',
      'Détergents et savons',
      'Soude Caustique',
      'Débouche-conduit à base de soude caustique',
      'Chlore',
      'Clorox',
      'Javex',
      'Domestos',
      'Lysol Blanchissant',
      'OxiClean',
      'Soude Caustique GIL',
      'Soude Caustique Liquide Recochem',
      'Débouche-Tuyau Drano Max',
      'Débouche-Conduit CLR',
      'Chlore Granulaire HTH',
      'Chlore Liquide Aqua',
      'Zep Industrial Cleaner',
      'Mr. Clean Pro',
      'Ecolab Inox Cleaner',
      'Windex Alcalin',
      'Liquid-Plumr',
      'Lime-A-Way',
      'Iron Out',
      'Zep Heavy Duty Degreaser',
      'Coil Clean',
      'Nu-Calgon Evaporator Cleaner',
      'Rectorseal Coil Cleaner',
      'Ridgid Pump Cleaner',
      'CRC Compressor Cleaner',
      'Spray Nine Fan Cleaner',
      'Simple Green Filter Cleaner',
      'WD-40 Specialist Valve Cleaner',
      'Loctite Joint Cleaner',
      'Hercules Pipe Cleaner',
      'Permatex Sealant Cleaner',
      'CRC Conveyor Cleaner',
      'Zep Tank Cleaner',
      'Ecolab Chain Cleaner',
      'Lubriplate Hydraulic Cleaner',
      'CRC QD Pneumatic Cleaner',
      'Contact Cleaner CRC',
      'Evapo-Rust Passivant',
      'Rust-Oleum Inhibitor',
      'SpillTech Acid Neutralizer',
      'AbsorbTech Base Neutralizer',
      'Brasso Metal Cleaner',
      'Tap Magic Tool Cleaner',
      'Gunk Engine Cleaner',
      'Mold Cleaner CRC',
      'Boiler Cleaner Zep',
      'Jet Spray Turbine Cleaner',
      'Krud Kutter Surface Cleaner',
      'Goof Off Paint Cleaner',
      'Minwax Varnish Cleaner',
      'MG Chemicals PCB Cleaner',
    ],
    directive: '',
  ),
  Category(
    name: 'PCD Acides',
    binColor: 'bleu',
    icon: Icons.science,
    items: [
      'Débouche-conduit à base acide',
      'Grosses Batteries',
      'Acide de batterie',
      'Liquide de frein',
      'Acide chlorhydrique',
      'Acide fluorhydrique',
      'Produits nettoyant pour Métaux',
      'Acide a piscine',
      'Nettoyants pour cuvette',
      'Liquid Fire',
      'Rooto Acid Drain Cleaner',
      'Recochem Acide Chlorhydrique',
      'LabChem Acide Fluorhydrique',
      'Chemfax Acide Sulfurique',
      'Crown Acide Phosphorique',
      'Fisher Acide Nitrique',
      'Wood Bleach Acide Oxalique',
      'PureChem Acide Citrique',
      'Glacial Acide Acétique',
      'HTH Acide Piscine',
      'Trojan Batterie',
      'Yuasa Batterie',
      'Prestone DOT 3',
      'Motul RBF',
      'Lysol Power Toilet Cleaner',
      'Muriatic Acid Cleaner',
      'Tarn-X Metal Cleaner',
      'Zep Acid Glass Cleaner',
      'CLR Pro',
      'Rust Remover Iron Out',
      'Diversey Acid Floor Cleaner',
      'Nu-Brite Coil Cleaner',
      'Evap Foam',
      'CoilJet',
      'Ridgid Acid Cleaner',
      'CRC Acid Wash',
      'Spray Nine Acid Fan Cleaner',
      'Zep Acid Filter Cleaner',
      'Loctite Acid Cleaner',
      'Permatex Acid Cleaner',
      'Hercules Acid Pipe Cleaner',
      'Gasket Remover',
      'CRC Acid Conveyor Cleaner',
      'Zep Acid Tank Cleaner',
      'Ecolab Acid Chain Cleaner',
      'Acid Flush Hydraulic Cleaner',
      'Acid Spray Pneumatic Cleaner',
      'Acid Contact Cleaner',
      'Evapo-Rust Acid Passivant',
      'Rust Converter',
      'Klean-Strip Décapant',
      'MG Chemicals Acid PCB Cleaner',
      'Naval Jelly',
      'Gunk Acid Engine Cleaner',
      'Acid Blade Cleaner',
      'Acid Mold Cleaner',
      'Acid Boiler Cleaner',
      'Acid Jet Spray',
      'Goof Off Pro',
    ],
    directive: '',
  ),
  Category(name: 'PCD Solvants/Peintures', binColor: 'bleu', icon: Icons.format_paint, items: ['Alcool',
      'Kérosène',
      'Huile pour moteur',
      'Dissolvant pour vernis à ongles',
      'Peinture',
      'Dissolvant a peinture',
      'Goof OFF',
      'Distillat de pétrole',
      'Propane',
      'Butane',
      'Essence',
      'Solvant',
      'Teinture et produit de finition pour le bois',], directive: ''),
  Category(name: 'PCD Produits de maison', binColor: 'bleu', icon: Icons.cleaning_services, items: [
    'Ammoniaque',
    'Aérosol',
    'Désodorisants en Aérosol',
    'Antigel',
    'Produits pour artisanat',
    'Polis à meubles',
    'Colles/adhésifs',
    'Peroxyde Hydrogène',
    'Insecticides',
    'herbicides',
    'Fertilisants',
    'Nettoyants pour four',
    'Produit pour animaux domestique',
  ], directive: ''),
  
  // Bac bleu
  Category(name: 'Vêtements', binColor: 'bleu', icon: Icons.checkroom, items: [
    'Vêtements (femmes, hommes, enfants)',
    'Chandail',
    'Pantalon',
    'Bermuda',
    'Pantalon court',
    'Robe',
    'Jupe',
    'Maillot de bain',
    'Bikini',
    'Couverture',
    'Manteau',
    'Manteau d’hiver avec pantalon d’hiver',
    'Legging',
    'Léotard',
    'Rideaux',
    'Draps',
    'Ensemble de drap (drap + tête d’oreiller + couvre-lit etc.)',
    'Grande serviette de bain (serviette de corps)',
    'Soutien-Gorge seulement (pas les petites culottes, boxers, monokinis)',], directive: ''),
  Category(name: 'Gros Morceaux (HG)', binColor: 'bleu', icon: Icons.chair_alt, items: [], directive: 'Tout ce qui est trop grand et qui n’entre pas dans les autres types de bac. Toujours vérifier d’abord que c’est bien le cas avant de mettre l’objet dans le bac bleu.'),

  // Bac noir
  Category(
    name: 'Électronique/Électrique',
    binColor: 'noir',
    icon: Icons.tv,
    items: [
      'Téléviseurs',
      'Climatiseurs',
      'Grille-pain',
      'Fours micro-ondes',
      'Robots culinaires',
      'Ordinateur de bureau',
      'Ordinateur de Gaming',
      'Serveur',
      'Workstation',
    ],
    directive: "Mettre dans cette catégorie tout objet qui fonctionne avec de l'électricité, qu'il soit filaire ou à batterie mais qui n'entre pas dans un bac gris.Les items comme les Écrans de télé 42″ et plus & Climatiseurs sur roulettes iront dans le bac bleu Gros morceaux",
  ),
];

class Category {
  final String name;
  final String binColor;
  final IconData icon;
  final List<String> items;
  final String directive;

  Category({
    required this.name,
    required this.binColor,
    required this.icon,
    required this.items,
    required this.directive,
  });
}

class CategoriesPage extends StatelessWidget {
  const CategoriesPage({super.key});

  Color getBinColor(String bin) {
    switch (bin) {
      case 'gris':
        return Colors.grey[600]!;
      case 'bleu':
        return Colors.blue[700]!;
      case 'noir':
        return Colors.black;
      default:
        return Colors.transparent;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Catégories')),
      backgroundColor: Colors.white,
      body: Column(
        children: [
          Expanded(
            child: GridView.count(
              crossAxisCount: 2,
              padding: EdgeInsets.all(16),
              childAspectRatio: 1.2,
              children: categories.map((cat) {
                final showBin = cat.binColor != 'aucun';
                final cardContent = Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(cat.icon, size: 20, color: showBin ? getBinColor(cat.binColor) : Colors.red),
                    SizedBox(height: 8),
                    Text(
                      cat.name,
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                        color: Colors.blue[800],
                      ),
                    ),
                    SizedBox(height: 4),
                    if (showBin)
                      Container(
                        padding: EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                        decoration: BoxDecoration(
                          color: getBinColor(cat.binColor),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Text(
                          'Bac ${cat.binColor}',
                          style: TextStyle(color: Colors.white, fontSize: 12),
                        ),
                      ),
                    if (!showBin)
                      Container(
                        padding: EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                        decoration: BoxDecoration(
                          color: Colors.red,
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Text(
                          'Non accepté',
                          style: TextStyle(color: Colors.white, fontSize: 12),
                        ),
                      ),
                  ],
                );
                return InkWell(
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => CategoryDetailPage(category: cat),
                      ),
                    );
                  },
                  child: Card(
                    color: Colors.amber[200],
                    elevation: 4,
                    margin: EdgeInsets.all(8),
                    child: Container(
                      constraints: BoxConstraints(minHeight: 120),
                      child: cardContent,
                    ),
                  ),
                );
              }).toList(),
            ),
          ),
        ],
      ),
    );
  }
}

class CategoryDetailPage extends StatefulWidget {
  final Category category;
  const CategoryDetailPage({super.key, required this.category});

  @override
  State<CategoryDetailPage> createState() => _CategoryDetailPageState();
}

class _CategoryDetailPageState extends State<CategoryDetailPage> {
  String query = '';

  @override
  Widget build(BuildContext context) {
    final filteredItems = query.isEmpty
        ? widget.category.items
        : widget.category.items
            .where((item) => item.toLowerCase().contains(query.toLowerCase()))
            .toList();

    final showBin = widget.category.binColor != 'aucun';

    return Scaffold(
      appBar: AppBar(title: Text(widget.category.name)),
      backgroundColor: Colors.white,
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Icon(widget.category.icon, size: 60, color: showBin ? Colors.blue[800] : Colors.red),
              SizedBox(height: 16),
              Text(
                widget.category.name,
                style: TextStyle(
                  fontSize: 22,
                  fontWeight: FontWeight.bold,
                  color: Colors.blue[800],
                ),
              ),
              SizedBox(height: 16),
              if (widget.category.directive.isNotEmpty)
                Padding(
                  padding: const EdgeInsets.only(bottom: 12.0),
                  child: Text(
                    widget.category.directive,
                    style: TextStyle(fontSize: 16, color: Colors.blue[800], fontWeight: FontWeight.w500),
                  ),
                ),
              TextField(
                decoration: InputDecoration(
                  labelText: 'Rechercher un item',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.search),
                ),
                onChanged: (value) => setState(() => query = value),
              ),
              SizedBox(height: 16),
              if (filteredItems.isNotEmpty)
                ...filteredItems.map((item) => Padding(
                  padding: const EdgeInsets.symmetric(vertical: 2.0),
                  child: Text("- $item", style: TextStyle(fontSize: 15)),
                ))
              else
                Padding(
                  padding: const EdgeInsets.symmetric(vertical: 8.0),
                  child: Text("Aucun item trouvé.", style: TextStyle(fontSize: 15, color: Colors.grey)),
                ),
              SizedBox(height: 16),
              if (showBin)
                Container(
                  padding: EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: Colors.blue[800],
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    'Bac ${widget.category.binColor}',
                    style: TextStyle(color: Colors.white, fontSize: 14),
                  ),
                ),
              if (!showBin)
                Container(
                  padding: EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: Colors.red,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    'Non accepté',
                    style: TextStyle(color: Colors.white, fontSize: 14),
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}